In [ ]:
#!C:\Users\kon3254>conda install pytorch -c pytorch

In [2]:
import torch

In [3]:
print(torch.__version__)

0.4.1


In [6]:
tensor_array = torch.Tensor([[1,2], [4,5]])
tensor_array

tensor([[1., 2.],
        [4., 5.]])

In [7]:
tensor_uninitalized = torch.Tensor(3,3)

In [15]:
tensor_uninitalized

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [   nan,    nan, 0.0000]])

In [14]:
tensor_uninitalized.shape

torch.Size([3, 3])

In [11]:
torch.numel(tensor_uninitalized)

9

In [12]:
torch.numel(tensor_array)

4

In [24]:
import numpy as np
import pandas as pd
import random
random.seed(1)  # doesn't work

In [28]:
tensor_initilized = torch.rand(2,3)
tensor_initilized

tensor([[0.3610, 0.9901, 0.2684],
        [0.5536, 0.9143, 0.9140]])

In [38]:
tensor_int2 = torch.randn(5,3)
tensor_int2

tensor([[ 1.1330, -0.4099,  0.2386],
        [-0.3089, -0.2410,  0.4619],
        [-0.5534, -0.9719,  0.2848],
        [ 0.6637,  0.5503,  1.3497],
        [ 0.0520,  1.6512, -1.0072]])

In [ ]:
#NOTE:rand() returns random values between 0 and 1. The random values would follow a uniform distribution and 
#     hence the mean value would be 0.5

#randn() returns random values between -infinity and +inifinity. The random values would follow a 
# normal distribution with a mean value 0 and a standard deviation 1.

In [35]:
tensor_int = torch.randn(5,3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  0],
        [-1,  0,  1],
        [ 1,  0,  0],
        [ 0, -4,  0],
        [ 0,  0,  0]], dtype=torch.int32)

In [39]:
tensor_long = torch.LongTensor([1.1111,2.2222,3.3333])
tensor_long

tensor([1, 2, 3])

In [40]:
tensor_byte = torch.ByteTensor([0, 261,1, -5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [43]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
tensor_zeros = torch.zeros(5,5)
tensor_zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
tensor_zeros2 = torch.zeros(1,5)
tensor_zeros2

tensor([[0., 0., 0., 0., 0.]])

In [50]:
tensor_zeros3 = torch.zeros(5,1)
tensor_zeros3

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [52]:
tensor_eye = torch.eye(4)  # diagonals are 1's and eveything else 0's
tensor_eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [53]:
torch.nonzero(tensor_eye)

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [54]:
torch.nonzero(tensor_zeros)

tensor([], dtype=torch.int64)

In [55]:
torch.nonzero(tensor_byte)

tensor([[1],
        [2],
        [3]])

In [57]:
tensor_int.shape

torch.Size([5, 3])

In [58]:
tensor_duplicate = torch.ones_like(tensor_int) # creates ones tensor with same shape as tensor_int
tensor_duplicate

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

### Inplace & out-of-place operations

In [ ]:
#All inplace operations have '_' suffix

In [63]:
intial_tensor = torch.rand(3,3)
intial_tensor

tensor([[0.9240, 0.6312, 0.6151],
        [0.4279, 0.6256, 0.1732],
        [0.3360, 0.8445, 0.8033]])

In [65]:
second_tensor = intial_tensor.fill(3)

AttributeError: 'Tensor' object has no attribute 'fill'

In [61]:
intial_tensor.fill_(3)  #inplace 

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [62]:
intial_tensor

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [66]:
new_tensor = torch.rand(4,2)
new_tensor

tensor([[0.4523, 0.0586],
        [0.8700, 0.0968],
        [0.4854, 0.9217],
        [0.9696, 0.8276]])

In [67]:
new_tensor2 = new_tensor.add(5) #out
new_tensor2

tensor([[5.4523, 5.0586],
        [5.8700, 5.0968],
        [5.4854, 5.9217],
        [5.9696, 5.8276]])

In [68]:
new_tensor

tensor([[0.4523, 0.0586],
        [0.8700, 0.0968],
        [0.4854, 0.9217],
        [0.9696, 0.8276]])

In [69]:
new_tensor.add_(5)  #inplace

tensor([[5.4523, 5.0586],
        [5.8700, 5.0968],
        [5.4854, 5.9217],
        [5.9696, 5.8276]])

In [70]:
new_tensor

tensor([[5.4523, 5.0586],
        [5.8700, 5.0968],
        [5.4854, 5.9217],
        [5.9696, 5.8276]])

### Using numpy arrays

In [121]:
numpy_array = np.array([[1,2,3,4.0, 5, 6,7]] )
numpy_array

array([[1., 2., 3., 4., 5., 6., 7.]])

In [122]:
numpy_array.shape

(1, 7)

In [123]:
numpy_array2 = np.array([1,2,3,4.0, 5, 6,7] )
numpy_array2

array([1., 2., 3., 4., 5., 6., 7.])

In [124]:
numpy_array2.shape

(7,)

In [125]:
numpy_array3 = np.array([[], [1,2,3,4.0], [5, 6,7]] )
numpy_array3

array([list([]), list([1, 2, 3, 4.0]), list([5, 6, 7])], dtype=object)

In [126]:
numpy_array3.shape

(3,)

In [127]:
tensor_from_numpy_array = torch.from_numpy(numpy_array)
tensor_from_numpy_array

tensor([[1., 2., 3., 4., 5., 6., 7.]], dtype=torch.float64)

In [128]:
tensor_from_numpy_array.shape

torch.Size([1, 7])

In [129]:
array_regenerated_from_tensor = tensor_from_numpy_array.numpy()
array_regenerated_from_tensor

array([[1., 2., 3., 4., 5., 6., 7.]])

In [130]:
array_regenerated_from_tensor.shape

(1, 7)

In [131]:
numpy_array

array([[1., 2., 3., 4., 5., 6., 7.]])

In [132]:
numpy_array[0,1] = 0

In [133]:
tensor_from_numpy_array   # the tensor is updated as it refers to the numpy array

tensor([[1., 0., 3., 4., 5., 6., 7.]], dtype=torch.float64)

In [135]:
tensor2 = torch.rand(2,3)
tensor2

tensor([[0.6461, 0.7896, 0.2445],
        [0.5928, 0.8073, 0.8690]])

In [142]:
tensor2[0,0]

tensor(0.6461)

In [143]:
tensor2[1,2]

tensor(0.8690)

In [144]:
tensor2[:, 2] #all rows, second column

tensor([0.2445, 0.8690])

In [145]:
tensor2.size()

torch.Size([2, 3])

In [146]:
tensor2.shape

torch.Size([2, 3])

In [150]:
tensor2_view = tensor2.view(3,2)  # refers to original tensor
tensor2_view

tensor([[0.6461, 0.7896],
        [0.2445, 0.5928],
        [0.8073, 0.8690]])

In [151]:
tensor2.view(6) # refers to original tensor

tensor([0.6461, 0.7896, 0.2445, 0.5928, 0.8073, 0.8690])

#### Sorting a tensor

In [152]:
tensor2

tensor([[0.6461, 0.7896, 0.2445],
        [0.5928, 0.8073, 0.8690]])

In [153]:
sorted_tensor, sorted_indices = tensor2.sort()  # same as  torch.sort(tensor2)

In [154]:
sorted_tensor

tensor([[0.2445, 0.6461, 0.7896],
        [0.5928, 0.8073, 0.8690]])

In [155]:
sorted_indices

tensor([[2, 0, 1],
        [0, 1, 2]])

In [159]:
tensor2.sort(dim=0)  #columns sorted in ascending order

(tensor([[0.5928, 0.7896, 0.2445],
         [0.6461, 0.8073, 0.8690]]), tensor([[1, 0, 0],
         [0, 1, 1]]))

In [160]:
tensor2.sort(dim=1)  #rows sorted in ascending order

(tensor([[0.2445, 0.6461, 0.7896],
         [0.5928, 0.8073, 0.8690]]), tensor([[2, 0, 1],
         [0, 1, 2]]))

### AUTOGRAD

In [ ]:
#NOTE: Autograd is a core package in pytorch for automatic differentition; is used for 
#      calculating gradients for backward propogation
#      It remembers all executed operations in the forward phase and replays them in the backward phase